export const FETCH_ALL_MUSICIAN = 'FETCH_ALL_MUSICIAN'
export const SHOW_MUSICIAN_DATA = 'SHOW_MUSICIAN_DATA'
export const FAILED_GET_ALL_MUSICIAN = 'FAILED_GET_ALL_MUSICIAN'
export const SUCCES_ALL_MUSICIAN = 'SUCCESS_ALL_MUSICIAN'